### ISSUE TITLE
Day 32 Lab - Missing technical requirements

### ISSUE THREAD

**Issue by elaewin** [brlittle86/core-data-hotel#4]
You are still missing the following technical requirements:

* `DatePickerViewController` should have both `startDate` and `endDate` date pickers. All views should get their proper layout from `Auto Layout` and **not** by assigning their frame.  
  * **You have these, but without some kind of label, it's hard to tell what the pickers are for, and it's unclear that certain dates are not allowed.**
 
* implement a `Done` button to allow the user to book the reservation.  
  * **The `selector` for this button should create a new `Reservation` and persist it to Core Data.**

**Comment by brlittle86** [comment]
Completed in wednesday-lab, will re-submit lab
